title_tag_text: ubuntu graphics suite
h1_tag_text: mooniak
safe: false
lsi: false
pygments: true
 
- baseurl: http://mooniak.com/ubuntu-graphics-suite

paginate: 10

exclude:
  - README.md

# About/contact
author:
  name:              Pathum Egodawatta
  url:               https://twitter.com/pathumego
  email:             pathum@mooniak.com
  version:             0.0.1
